sudo: required
services:
  - docker

notifications:
  slack: nugentlab:ZRjjbU7agpY8L6jJxcCzVn2b

script:
  - docker build . -t sidworld/neat
  - docker run sidworld/neat

after_script:
  - docker images

before_deploy:
  - docker login -u "neatomater" -p "neatomater"
  
deploy:
  provider: script
  script: docker push sidworld/neat
  on:
    branch: master
    

